### ISSUE TITLE
Regions get removed on restart

### ISSUE THREAD

**Issue by JustGoinPostal** [alex9849/advanced-region-market#155]
Whenever I fully set up my regions and the server restarts my regions are still in the regions file but are not identified by the plugin anymore.

**Comment by alex9849** [comment]
Can you submit your regions file with regions?

**Comment by JustGoinPostal** [comment]
[regions.txt](https://github.com/alex9849/advanced-region-market/files/13881951/regions.txt)
here is it in a text file wont let me upload a yml file

**Comment by alex9849** [comment]
Your problem is, that your world name contains dots. In the spigot api a dots is a splitting character which starts a new configuration section and therefore and indentation. This messes up the regions file. Rename you wold such that the dots are removed from the name and your problem should be gone.

**Comment by JustGoinPostal** [comment]
Is there any other way to do this within your plugin because changing my world name is going to mess up all of my current plugins.

**Comment by alex9849** [comment]
Unfortunately not. The dot is a separator character in the spigot yaml library and there is no escape character. So I can't really change anything. The only option would be to create one folder per world. But that would require huge changes in the plugin code itself. Also, at the moment I'm just maintaining the plugin and not actively adding features. So this won't be implemented in the near future.
