### ISSUE TITLE
Recalculate price on sign without deleting it

### ISSUE THREAD

**Issue by Bloodlex** [alex9849/advanced-region-market#25]
Hey,
It would be very nice to have a feature to recalculate the price after changing the region size :)

**Comment by alex9849** [comment]
You shouldn't change the size of a region after you've created it. Worldguard deletes its regions and recreates the if you redefine them. ARM has no (efficient) way to find out that the region-object has changed in worldguard. This means it also won't update its schematics and the plugin needs to be reloaded in order to even start using the new region-object
