### ISSUE TITLE
Allow BUY/SELL regions to have their price set via command

### ISSUE THREAD

**Issue by Technofied** [alex9849/advanced-region-market#36]
Reason: Currently rent regions are able to have their prices set via /arm setprice, but we cannot do the same for any buy/sell region without making a sign to create and define the price.

Proposal: Be able to run this command to set a region's price - /arm setprice regionname price

**Comment by alex9849** [comment]
The setprice command can be used to also set prices for other region-types. You always have to specify a full rent-price (including extendtime and maxrenttime)
The additional arguments will be ignored if the sell-type of the region doesn't need the additional information. The additional data is required because you can theoretically change the price for multiple regions (regionkinds) at once and you may have multiple regions with different sell-types in one regionkind)
