### ISSUE TITLE
feat: database support

### ISSUE THREAD

**Issue by Silthus** [alex9849/advanced-region-market#48]
First off thanks for the awesome region plugin! I really enjoy the features and quality it provides. However for me it has one thing missing: database support.

In our server everything is managed with git and only static config files are are placed into the plugins data directory.
Database support would also give users the option to display region stats on their website.

I am also willing to help on this and draft a PR if wanted.

And if you are worried about writing SQL queries or handling database connections, I have just the right tool for you ;)

https://github.com/Silthus/ebean-wrapper

The database feature could be optionally enabled if the wrapper is detected and configurable via the config.

The only thing needed for this to work is a short connect method in your plugin: https://github.com/Silthus/sStats/blob/55807b00c50fd2629bd4793f68a07ae31d6a1778/src/main/java/net/silthus/sstats/StatsPlugin.java#L56

And then you need to setup and store your entities (which you can completely reuse even without database support): https://github.com/Silthus/sStats/blob/master/src/main/java/net/silthus/sstats/entities/PlayerSession.java

Let me know if I should send a PR.

**Comment by alex9849** [comment]
I've also thought about adding support for MySql databases in the past. I've never added it, because this plugin heavily depends on WorldGuard which doesn't supports MySql in a stable way. Ref. --> https://worldguard.enginehub.org/en/latest/regions/storage/

I would also have to fetch the whole database on plugin startup, because I don't want execute heavy SQL commands every tick. This would mean, that the plugin wouldn't "hot react" to changes that you make manually in the database. That would require a reload. While the plugin runs, that database can only be used to read, but not to write data.

So I think databse support would be somthing nice, but I don't believe, that it would really create a significant value compared to the effort, that it would require to implement it.

If you want you can contact me on discord (My username is alex9849#0602) if you want to implement database support, or want to talk about it (since it isn't a small task).
