### ISSUE TITLE
Making performance better with higher interval

### ISSUE THREAD

**Issue by omit01** [alex9849/advanced-region-market#63]
I was looking with our developers to timings of our server. We were wondering about the high impact of `net.alex9849.arm.AdvancedRegionMarket$$Lambda$5878 (interval:1)`, which was around 5%. After searching for the value of the interval and turning it up to 20, the usage fell to 1 a 2%.

Our suggestion is to optimize the plugin by making the interval configurable.

**Comment by kilian544** [comment]
I have looked through your code and while the idea to make a queue for the checks you do seems like a good idea it is overkill for the largest section of your users. You'd need some insane amount of regions to get any real performance gain from this. Besides this I believe the cullprit is all the arrays and Lists you instantiate, these result in memory allocations which are some of the slower operations. I also caught a glimpse of you retrieving chunks alot, this is also a pretty memory intensive thing.

I'll take a second look at it somewhen this week and update if I find anything remarkable.

**Comment by alex9849** [comment]
It may seem a bit overkill, but the system actually helps to distribute the computing load to as many ticks as possible.
ARM updates all signs of all regions in a defined interval. (It also checks if a region has expired, but I this is not why the system exists)
Updating signs is quite a heavy task and if the sign that should be updated is located in a chunk that is not loaded, the chunk has to be loaded from your hard drive. Doing this with many signs in short intervals may cause your server to completely freeze and crash. So AdvancedRegionMarket does the following:
 - Signs don't need to be updated if no player sees them. If a player may see them, the chunk where the sign is located should be already loaded. So ARM only updated signs that are already loaded and don't need to be loaded first.
 - We have an interval in which all regions should be updated. (By default 40 ticks). We don't want to do all the work in one single tick, so we update a subset of all our regions in every tick. 
 - Since we know, that region-signs that are in the same chunk may be updated in the same tick, while other ticks don't have to update any sign because all the chucks are not loaded, we try to update signs that are in the same chunk in different update subsets. If you for example have a wall with all region-signs, your region-signs will very likely be updated in different ticks. 

Memory shouldn't be a real problem. We are talking about data in the kb-area. The RegionManager stores every region in 3 different collections (per reference, not per copy). Once in the worldChunkRegionMap (needed for fast mapping of locations), once in the YamlFileManager, and once in the updateScheduler.

One thing that may cause spikes in your timings is region-restoration. If a region gets updated it will also be checked if the region has expired. If it has expired ARM will restore the region with WorldEdit. You know that pasting WordEdit schematics can cause lags, but since that doesn't happen very often it shouldn't be such a huge problem either. But nevertheless it can be seen in the timings. 

If you find a way to improve the performance of the plugin I'm open to your ideas and maybe also pull-requests. But you should keep in mind that there are servers with multiple thousands regions.

**Comment by n1ouse** [comment]
Didn't get around to it sooner but I did some testing, and your claim that there are servers out there that have multiple thousands of regions seems unlikely to me. When ran on my system, which surely isn't the best but still, the server falls flat on its face around 1500 shops. These are simple "single-cuboid" shops.

I also did some testing with different implementations, one if which was @omit01's, this ran the fastest if I recall correctly but in reality this setup is not comparable to yours since it slashes the amount of actual updates a couple times...

Furthermore I tried remove your sorting to "spread" the chunks which to my surprise ran worse. Which to me seems really counter-intuative, this would mean there is a possibility that the sign needs to be retrieved once again would it not? Could you clarify on this?

I couldn't find any code that limits updates to signs that the player can actually see. Why wouldn't you update updates of signs to 3x3 chunk's around any active player? And have you done any investigation as to why updating signs is so expensive? Surely there has to be some way to optimize performance...

Anyways, @alex9849, thanks for this plugin, our players really enjoy it!
