### ISSUE TITLE
[FEATURE REQUEST] Shop Integration

### ISSUE THREAD

**Issue by untuned** [alex9849/advanced-region-market#69]
I would like ARM to support the following plugin: https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/

It's API is available here: https://www.spigotmc.org/wiki/shop-developer-wiki/

I would like to be able to set if shops can be created in ARM regions, and to properly remove them if the region is reset.

**Comment by alex9849** [comment]
I no longer maintain the "Shop Bridge" plugin. The reason is that there simply are so many (Item)-shop plugins but not so many region shop plugins. It's a lot simpler for every shop-plugin-developer to integrate with ARM then it is for me to integrate with all existing shop plugins. Also the plugin that you mentioned is a premium plugin which the author gets money for. ARM is free.
